apiVersion: v1
entries:
  memphis:
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.4.1
    created: "2023-12-13T14:08:36.557338229Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: 22c635560ac6358abd3f8c0a99420d107719e121645772f4ee52c8f9af5a710e
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.4.0.tgz
    version: 1.4.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.4.0
    created: "2023-12-13T14:08:36.552279592Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: e1ba0a9bc147694908b1bc1e423f6748021d0e12be59f7fb15bab5e1fbc9c6bd
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.3.0.tgz
    version: 1.3.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.3.1
    created: "2023-12-13T14:08:36.546357567Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: b0826a8819aa9f5163e99bada65abd3376173f8ae8b440815af0547b3f8660ab
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.4.tgz
    version: 1.2.4
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.3.0
    created: "2023-12-13T14:08:36.541221697Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: 9b466ffe9206be6b98562734b01808baf9204603e92e848472bacac023dd66d8
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.3.tgz
    version: 1.2.3
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.2.0
    created: "2023-12-13T14:08:36.535329626Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: 285a5cae3790b01950324256fd8173d41f168836a751da6425c5d8e49e6c35eb
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.2.tgz
    version: 1.2.2
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.2.0
    created: "2023-12-13T14:08:36.529618242Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: f6e547f4fc5d23e13fe653bd0a8a2471f541b2fa48906303bc533ec2e9da4c8d
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.1.tgz
    version: 1.2.1
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.2.0
    created: "2023-12-13T14:08:36.524465856Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: 39e84af63bd07045635b494e7d00b93f9206a8cb8099200bc021ef8e9ab6a089
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.0.tgz
    version: 1.2.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.1.1
    created: "2023-12-13T14:08:36.518688567Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: 12037818a8244c5a46cb81c2b6b705112f1974c361a7e02960df8ea14c39e469
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.1.1.tgz
    version: 1.1.1
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.1.0
    created: "2023-12-13T14:08:36.513526118Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: d7e16f52a13fa68cb66ef80a8b81eeafbcb1e8c812c5e99e34be54bba36b6f53
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.1.0.tgz
    version: 1.1.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.0.3
    created: "2023-12-13T14:08:36.507772061Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: de20efbde1d7e0dc757195cf1644333fad5a3d7769d763112e6957b9d18fa437
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.0.3.tgz
    version: 1.0.3
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.0.1
    created: "2023-12-13T14:08:36.502664784Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: 86488895624a1430996b0a2c25dae90ef1b16ccf8ea10317aaa75094c0e1f545
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.0.1.tgz
    version: 1.0.1
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2023-12-13T14:08:36.497003889Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: '>1.0.0-0'
    description: Memphis.dev Official Helm chart
    digest: 2b67fb6ba49bbbc717015bb56fe8df25c4505079bfa44c94dca9e655f8c2de6a
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.0.0.tgz
    version: 1.0.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 0.4.5
    created: "2023-12-13T14:08:36.491837473Z"
    description: Memphis.dev Official Helm chart
    digest: e3e2ca1f38e7072aea1cbe9eeaf3c79c849289422e340960b56709056a1dea0f
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.5.tgz
    version: 0.4.5
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2023-12-13T14:08:36.490194897Z"
    description: Memphis.dev Helm chart
    digest: 6cf106e15fdfe86124e30afd91f036cd28d2a549fa01eba11bb08d35eb9c953e
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.4.tgz
    version: 0.4.4
  - apiVersion: v2
    appVersion: 0.4.3
    created: "2023-12-13T14:08:36.488984193Z"
    description: Memphis.dev Helm chart
    digest: be47621169bdd4942b954945ae97eb88041ae1220165aad628648dd7b9b3d7e7
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.3.tgz
    version: 0.4.3
  - apiVersion: v2
    appVersion: 0.4.2
    created: "2023-12-13T14:08:36.487825432Z"
    description: Memphis.dev Helm chart
    digest: 3a17890606d0eb961f17a88fc5a9d2258d2071745ba21d8864946a50ed7e3ebb
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 0.4.1
    created: "2023-12-13T14:08:36.486645989Z"
    description: Memphis.dev Helm chart
    digest: 3901e5059d04a93f2afef1e66f0f097610c4cf41ec8f85e030c3b4749a0b1c9b
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-12-13T14:08:36.485482497Z"
    description: Memphis.dev Helm chart
    digest: abe8ef969af061633e0566bcc6f764a6175d74fe378d183a79394a3c4cf99b6b
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.6
    created: "2023-12-13T14:08:36.484325905Z"
    description: Memphis.dev Helm chart
    digest: 1463b0842ae745cfbc39bbbd59bf4aed1829610eb3305a5c9f0e8671fb9b433e
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.3.6.tgz
    version: 0.3.6
  - apiVersion: v2
    appVersion: 0.3.5
    created: "2023-12-13T14:08:36.48318367Z"
    description: Memphis.dev Helm chart
    digest: 9e05f5310f8456c431041b4e44f3570e4ae7d3bdab27d58f64c2486483951a2c
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.3.5.tgz
    version: 0.3.5
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2023-12-13T14:08:36.481973757Z"
    description: A Helm chart for Kubernetes
    digest: df8bc3b91ffd995e9ee743c4814ce37b38ac55f9366d16a07eebf5f05a03d462
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2023-12-13T14:08:36.480023419Z"
    description: A Helm chart for Kubernetes
    digest: d28563593f1577bb2381da7ec7a2b1a06301b04f30202ef00627127e21606657
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-13T14:08:36.478791122Z"
    description: A Helm chart for Kubernetes
    digest: 28d3abb9dbc8bb4e5d98e319af96bee39d7079373bc6f3ea1459f057557f07a2
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-12-13T14:08:36.477509926Z"
    description: A Helm chart for Kubernetes
    digest: 8a6ec6bc3d6cdaed00455814cceac7ee4096268d08e82bc9ca0af4cdf3a65cf1
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.2.0.tgz
    version: 0.2.0
generated: "2023-12-13T14:08:36.47610952Z"
