apiVersion: v1
entries:
  memphis:
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.2.0
    created: "2023-09-11T11:28:05.828759712Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: fbd5f9d4d1b7ba798fcbad6347d7954992713e6b31cbf30993f7a29d51b314dc
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.2.tgz
    version: 1.2.2
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.2.0
    created: "2023-09-11T11:28:05.823302778Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.5.2
    description: Memphis.dev Official Helm chart
    digest: f6e547f4fc5d23e13fe653bd0a8a2471f541b2fa48906303bc533ec2e9da4c8d
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/icon.png
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.1.tgz
    version: 1.2.1
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.2.0
    created: "2023-09-11T11:28:05.817333981Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: 39e84af63bd07045635b494e7d00b93f9206a8cb8099200bc021ef8e9ab6a089
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.2.0.tgz
    version: 1.2.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.1.1
    created: "2023-09-11T11:28:05.811760276Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: 12037818a8244c5a46cb81c2b6b705112f1974c361a7e02960df8ea14c39e469
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.1.1.tgz
    version: 1.1.1
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.1.0
    created: "2023-09-11T11:28:05.805432353Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: d7e16f52a13fa68cb66ef80a8b81eeafbcb1e8c812c5e99e34be54bba36b6f53
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.1.0.tgz
    version: 1.1.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.0.3
    created: "2023-09-11T11:28:05.79987841Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: de20efbde1d7e0dc757195cf1644333fad5a3d7769d763112e6957b9d18fa437
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.0.3.tgz
    version: 1.0.3
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.0.1
    created: "2023-09-11T11:28:05.793684957Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: 11.0.1
    description: Memphis.dev Official Helm chart
    digest: 86488895624a1430996b0a2c25dae90ef1b16ccf8ea10317aaa75094c0e1f545
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.0.1.tgz
    version: 1.0.1
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 1.0.0
    created: "2023-09-11T11:28:05.787892366Z"
    dependencies:
    - condition: metadata.enabled
      name: metadata
      repository: ""
      version: '>1.0.0-0'
    description: Memphis.dev Official Helm chart
    digest: 2b67fb6ba49bbbc717015bb56fe8df25c4505079bfa44c94dca9e655f8c2de6a
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-1.0.0.tgz
    version: 1.0.0
  - annotations:
      category: Streaming and messaging
      licenses: Memphis Business Source License 1.0
    apiVersion: v2
    appVersion: 0.4.5
    created: "2023-09-11T11:28:05.782502672Z"
    description: Memphis.dev Official Helm chart
    digest: e3e2ca1f38e7072aea1cbe9eeaf3c79c849289422e340960b56709056a1dea0f
    home: https://github.com/memphisdev/memphis
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    keywords:
    - data streaming
    - message broker
    - memphis
    - producer
    - consumer
    - cluster
    - high availability
    maintainers:
    - name: Memphis.dev
      url: https://k8s.memphis.dev/charts
    name: memphis
    sources:
    - https://github.com/memphisdev/memphis
    - https://www.memphis.dev
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.5.tgz
    version: 0.4.5
  - apiVersion: v2
    appVersion: 0.4.4
    created: "2023-09-11T11:28:05.781281645Z"
    description: Memphis.dev Helm chart
    digest: 6cf106e15fdfe86124e30afd91f036cd28d2a549fa01eba11bb08d35eb9c953e
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.4.tgz
    version: 0.4.4
  - apiVersion: v2
    appVersion: 0.4.3
    created: "2023-09-11T11:28:05.779755399Z"
    description: Memphis.dev Helm chart
    digest: be47621169bdd4942b954945ae97eb88041ae1220165aad628648dd7b9b3d7e7
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.3.tgz
    version: 0.4.3
  - apiVersion: v2
    appVersion: 0.4.2
    created: "2023-09-11T11:28:05.777741832Z"
    description: Memphis.dev Helm chart
    digest: 3a17890606d0eb961f17a88fc5a9d2258d2071745ba21d8864946a50ed7e3ebb
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.2.tgz
    version: 0.4.2
  - apiVersion: v2
    appVersion: 0.4.1
    created: "2023-09-11T11:28:05.776437488Z"
    description: Memphis.dev Helm chart
    digest: 3901e5059d04a93f2afef1e66f0f097610c4cf41ec8f85e030c3b4749a0b1c9b
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.1.tgz
    version: 0.4.1
  - apiVersion: v2
    appVersion: 0.4.0
    created: "2023-09-11T11:28:05.775202747Z"
    description: Memphis.dev Helm chart
    digest: abe8ef969af061633e0566bcc6f764a6175d74fe378d183a79394a3c4cf99b6b
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 0.3.6
    created: "2023-09-11T11:28:05.774027876Z"
    description: Memphis.dev Helm chart
    digest: 1463b0842ae745cfbc39bbbd59bf4aed1829610eb3305a5c9f0e8671fb9b433e
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.3.6.tgz
    version: 0.3.6
  - apiVersion: v2
    appVersion: 0.3.5
    created: "2023-09-11T11:28:05.772853656Z"
    description: Memphis.dev Helm chart
    digest: 9e05f5310f8456c431041b4e44f3570e4ae7d3bdab27d58f64c2486483951a2c
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.3.5.tgz
    version: 0.3.5
  - apiVersion: v2
    appVersion: 0.3.0
    created: "2023-09-11T11:28:05.771593389Z"
    description: A Helm chart for Kubernetes
    digest: df8bc3b91ffd995e9ee743c4814ce37b38ac55f9366d16a07eebf5f05a03d462
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 0.2.2
    created: "2023-09-11T11:28:05.770389665Z"
    description: A Helm chart for Kubernetes
    digest: d28563593f1577bb2381da7ec7a2b1a06301b04f30202ef00627127e21606657
    icon: https://memphis-public-files.s3.eu-central-1.amazonaws.com/Vector.jpg
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-11T11:28:05.769176632Z"
    description: A Helm chart for Kubernetes
    digest: 28d3abb9dbc8bb4e5d98e319af96bee39d7079373bc6f3ea1459f057557f07a2
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-11T11:28:05.767901927Z"
    description: A Helm chart for Kubernetes
    digest: 8a6ec6bc3d6cdaed00455814cceac7ee4096268d08e82bc9ca0af4cdf3a65cf1
    name: memphis
    type: application
    urls:
    - https://k8s.memphis.dev/charts/memphis-0.2.0.tgz
    version: 0.2.0
generated: "2023-09-11T11:28:05.765970473Z"
