apiVersion: /v1
kind: Service
metadata:
  name: strech-ui
  namespace: memphis-chart-tests
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: strech-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strech-ui
  namespace: memphis-chart-tests
  labels:
    app: strech-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strech-ui
  template:
    metadata:
      name: strech-ui
      labels:
        app: strech-ui
    spec:
      containers:
        - name: strech-ui
          image: 221323242847.dkr.ecr.eu-central-1.amazonaws.com/strech-ui-staging:latest
          ports:
            - containerPort: 80
          env:
          - name: ENVIRONMENT
            value: "staging"
