apiVersion: /v1
kind: Service
metadata:
  name: memphis-ui
  namespace: {{ include "nats.namespace" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.dashboard.port }}
      targetPort: 80
  selector:
    app: memphis-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memphis-ui
  namespace: {{ include "nats.namespace" . }}
  labels:
    app: memphis-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memphis-ui
  template:
    metadata:
      name: memphis-ui
      labels:
        app: memphis-ui
    spec:
      containers:
        - name: memphis-ui
          image: memphisos/memphis-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
          - name: ENVIRONMENT
            value: "staging"